import { Onest } from "next/font/google";
import "./globals.css";
import TopNav from "@/pages/shered/TopNav";
import MainNav from "@/pages/shered/MainNav";
import Footer from "@/pages/shered/Footer";

const onest = Onest({
    subsets: ["latin"],
    display: "swap",
    weight: ["100","200","300","400", "500", "600", "700", "800", "900",],
});

export const metadata = {
    title: "Cricket Winner",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={onest.className}>{children}</body>
        </html>
    );
}
